log-level: info
parameters:
- ingest:
    collector:
      hostname: 0.0.0.0
      port: 2055
    type: collector
  name: ingest_collector
- decode:
    type: json
  name: decode_json
    #- name: transform_generic
    #  transform:
    #    generic:
    #      rules:
    #      - input: SrcAddr
    #        output: SrcAddr
    #      - input: SrcPort
    #        output: srcPort
    #      - input: DstAddr
    #        output: DstAddr
    #      - input: DstPort
    #        output: dstPort
    #      - input: Proto
    #        output: proto
    #      - input: Bytes
    #        output: bytes
    #      - input: TCPFlags
    #        output: TCPFlags
    #      - input: SrcAS
    #        output: srcAS
    #      - input: DstAS
    #        output: dstAS
    #    type: generic
- name: transform_network
  transform:
    network:
      rules:
      - input: SrcAddr
        output: SrcK8S
        type: add_kubernetes
        parameters: srcK8S_labels
      - input: DstAddr
        output: DstK8S
        type: add_kubernetes
        parameters: srcK8S_labels
    type: network

- name: transform_ovn
  transform:
    ovn:
      ovn_sb_db: unix:/var/run/ovn/ovnsb_db.sock
      rules:
      - output: LogicalFlowUUID
        type: lflow_uuid
      - output: LogicalFlowMatch
        type: lflow_match
      - output: LogicalFlowActions
        type: lflow_actions
      - output: LogicalFlowPriority
        type: lflow_prio
      - output: LogicalFlowExternalID
        type: lflow_ext
      - output: LogicalFlowPipeline
        type: lflow_pipeline
      - output: LogicalFlowTable
        type: lflow_table
    type: ovn
   
- name: write_stdout
  write:
    type: stdout
#- name: write_loki
#  write:
#    loki:
#      url: http://loki.default.svc.cluster.local:3100
#      staticLabels:
#        job: flowlogs-pipeline
#    type: loki
pipeline:
- name: ingest_collector
- follows: ingest_collector
  name: decode_json
- follows: decode_json
  name: transform_network
- follows: transform_network
  name: transform_ovn
- follows: transform_ovn
  name: write_stdout
#- follows: transform_network
#  name: write_loki
