{
 "title": "Network Policies",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Network Policy Ingress ACCEPTs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (dstK8S_Name) (rate({job=\"flowlogs-pipeline\"} | json | __error__ = \"\" | NetworkPolicyAction = \"ACCEPT\" | NetworkPolicyDirection = \"ingress\" | unwrap Bytes[1m]))"
    }
   ]
  },
  {
   "title": "Network Policy Egress ACCEPTs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum by (srcK8S_Name) (rate({job=\"flowlogs-pipeline\"} | json | __error__ = \"\" | NetworkPolicyAction = \"ACCEPT\" | NetworkPolicyDirection = \"egress\" | unwrap Bytes[1m]))"
    }
   ]
  },
  {
   "title": "Network Policy Ingress  DROPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (dstK8S_Name,DstPort) (rate({job=\"flowlogs-pipeline\"} | json | __error__ = \"\" | NetworkPolicyAction = \"DROP\" | NetworkPolicyDirection = \"ingress\" | unwrap Bytes[1m]))"
    }
   ]
  },
  {
   "title": "Network Policy Egress  DROPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "sum by (srcK8S_Name,DstPort) (rate({job=\"flowlogs-pipeline\"} | json | __error__ = \"\" | NetworkPolicyAction = \"DROP\" | NetworkPolicyDirection = \"egress\" | unwrap Bytes[1m]))"
    }
   ]
  },
  {
   "title": "Top Ingress DROPed flows",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(5, sum by (srcK8S_Name, dstK8S_Name, SrcPort) (sum_over_time({job=\"flowlogs-pipeline\"} | json | __error__ = \"\" | NetworkPolicyAction = \"DROP\" | NetworkPolicyDirection = \"ingress\" | unwrap Packets [10m])))"
    }
   ]
  },
  {
   "title": "Top Egress DROPed flows",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 16 },
   "targets": [
    {
     "expr": "topk(5, sum by (srcK8S_Name, dstK8S_Name, DstPort) (sum_over_time({job=\"flowlogs-pipeline\"} | json | __error__ = \"\" | NetworkPolicyAction = \"DROP\" | NetworkPolicyDirection = \"egress\" | unwrap Packets [10m])))"
    }
   ]
  },
  {
   "title": "Top Network Policies",
   "type": "table",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (NetworkPolicyName) (sum_over_time({job=\"flowlogs-pipeline\"} | json | __error__ = \"\" | NetworkPolicyAction = \"ACCEPT\"  | unwrap Packets [10m]))"
    }
   ]
  },
  {
   "title": "Top Talkers",
   "type": "table",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (srcK8S_Name, dstK8S_Name, DstPort) (sum_over_time({job=\"flowlogs-pipeline\"} | json | __error__ = \"\" | NetworkPolicyAction = \"ACCEPT\"  | unwrap Packets [10m]))"
    }
   ]
  }
 ]
}